name: After Release

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  verify-release:
    name: "Verify Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: latest

      - uses: actions/checkout@v2

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Install release
        run: |
          swipl -g "pack_install('https://github.com/eshelyaron/debug_adapter/releases/download/${{ steps.get_version.outputs.version }}/debug_adapter-${{ steps.get_version.outputs.version-without-v }}.zip', [interactive(false)])" -t halt
