name: After Release

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  verify-release:
    name: "Verify Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: latest

      - uses: actions/checkout@v2

      - name: Install release
        run: yes | swipl -g "pack_install(debug_adapter)" -t halt
