name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: latest

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          autoreconf --install
          ./configure
          make
          make check

      - name: Build pack
        run: |
          make dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            *.zip
