name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: latest

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          cd test
          ls -la
          swipl server.plt
