name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SWI-Prolog Latest
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: latest

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          swipl test/server.pl

      - name: Install SWI-Prolog 8.2.4
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: stable
          swi-prolog-version: 8.2.4*

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          swipl test/server.pl
