name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SWI-Prolog Stable
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: stable

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          swipl -g "pack_install(.)" -t halt
          swipl test/server.pl
