name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install SWI-Prolog for Windows
        run: |
          choco install -y swi-prolog
          refreshenv

      - uses: actions/checkout@v2

      - name: Run Tests
        shell: cmd
        run: |
          swipl test/server.pl
