name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install SWI-Prolog for Windows
        run: |
          choco install swi-prolog
      - name: Set PATH
        shell: cmd
        run: |
          call refreshenv
          echo "CPATH=C:\Program Files\swipl\bin;C:\Program Files (x86)\swipl\bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          swipl test/server.pl
